[profile.default]
src = "src"
out = "out"
libs = ["lib"]
test = "test"
script = "script"
solc = "0.8.26"
evm_version = "cancun"
optimizer = true
optimizer_runs = 200
via_ir = false
bytecode_hash = "none"
cbor_metadata = false
ffi = false
fs_permissions = []
auto_detect_remappings = false
gas_limit = "300000000"

[profile.default.fuzz]
runs = 256

[profile.default.invariant]
runs = 24
depth = 48
fail_on_revert = false

[fmt]
line_length = 120
tab_width = 4
bracket_spacing = false
int_types = "long"
